config/routes.rb
Rails.application.routes.draw do
  resources :marks do
    collection do
      get :update_mark
    end
  end
  resources :discipline_sections
  resources :role_users do
    collection do
      get :mass_activation
      post :mass_activation_commit
    end
  end
  resources :community_newses
  resources :community_disciplines
  get 'students_api/load_from_json_file', as: :load_from_json_file_students_api
  post 'students_api/load_from_json_file'
  get 'students_api/load_to_json_file', as: :load_to_json_file_students_api
  #post 'students_api/load_to_json_file'

  get 'disciplines_api/load_from_json_file', as: :load_from_json_file_disciplines_api
  post 'disciplines_api/load_from_json_file'
  get 'disciplines_api/load_to_json_file', as: :load_to_json_file_disciplines_api

  get 'groups_api/load_from_json_file', as: :load_from_json_file_groups_api
  post 'groups_api/load_from_json_file'
  get 'groups_api/load_to_json_file', as: :load_to_json_file_groups_api

  get 'welcome/index', as: :index
  get 'welcome/insufficient_privileges', as: :ip

  resources :message_users
  resources :messages do
    member do
      get :show_file, as: :show_file
    end
  end
  resources :study_files
  resources :notices
  resources :institution_users
  resources :institutions
  resources :message_lists
  resources :community_contents
  resources :community_tabs
  resources :community_sections
  resources :community_users
  resources :communities do
    member do
      get :archiving
      get :dearchiving
    end
  end
  resources :disciplines
  resources :ranking_algorithms
  resources :groups
  resources :roles
  resources :terms
  root :to => 'welcome#index'
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discipline.rb
class Discipline < ApplicationRecord

  belongs_to :term
  belongs_to :ranking_algorithm
  has_many :discipline_sections
  has_many :community_disciplines
  has_and_belongs_to_many :institutions, dependent: :destroy

  SHORT_TYPES = {
    0 => 'Л',
    1 => 'ПР',
    2 => 'ЛАБ',
    3 => 'НИР'
  }

  DIS_TYPES = {
    0 => 'лекция',
    1 => 'семинар',
    2 => 'лабораторная работа',
    3 => 'курсовая/практическая/научно-исследовательская работа'
  }

  DIS_END = {
    0 => 'зачёт',
    1 => 'экзамен',
    2 => 'защита работы'
  }

  validates :discipline_name, presence: true, uniqueness: {scope: :discipline_end}
  validates :discipline_type, presence: true #, inclusion: { in: DIS_TYPES.keys }
  validates :discipline_end, presence: true, inclusion: { in: DIS_END.keys }
  validates :term_id, presence: true
  validates :ranking_algorithm_id, presence: true


  def discipline_type=(val)
    if val.kind_of?(Array)
      self[:discipline_type]=val.map(&:to_i)
    else
      self[:discipline_type]=val
    end
  end

  def Discipline.create_by_json(json)
    results = []
    begin
      json.each_with_index do |discipline_hash, i|
           begin
            u = Discipline.new(discipline_hash)
            u.save
            if u.errors.size > 0
              results << "Дисциплина № #{i + 1} содержит ошибки!"
            else
              results << "Дисциплина № #{i + 1} #{u.discipline_name} зарегистрирована."
            end
          rescue
            results << "Дисциплина № #{i + 1} содержит ошибки!"
          end
      end
    rescue
      results << 'JSON файл не корректен!'
    end
    results
  end

end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.all.page(params[:page]).per(10)
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)
    #raise discipline_params.inspect
    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Дисциплина успешно создана' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Дисциплина успешно обновлена' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    if (@discipline.discipline_sections.blank? && @discipline.community_disciplines.blank?)
      @discipline.destroy
      message = "Дисциплина успешно удалена"
      respond_to do |format|
        format.html { redirect_to disciplines_url, notice: message }
        format.json { head :no_content }
      end
    else
      message = "Произошла ошибка при удалении дисциплины: на данную дисциплину ссылаются другие объекты системы"
      respond_to do |format|
        format.html { redirect_to @discipline, notice: message }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:discipline_name, :discipline_end, :term_id, :ranking_algorithm_id, discipline_type: [])
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper

  def discipline_type_options(selected)
		options_for_select(Discipline::DIS_TYPES.map { |k, v| [v, k]}, selected)
  end

  def discipline_end_options(selected)
		options_for_select(Discipline::DIS_END.map { |k, v| [v, k]}, selected)
  end

  def term_options(selected)
		options_for_select(Term.all.map{ |tr| ["#{tr.term_name} ", tr.id] }, selected)
  end

  def ranking_algorithm_options(selected)
		options_for_select(RankingAlgorithm.all.map{ |ra| ["#{ra.algorithm_name} ", ra.id] }, selected)
  end

  def discipline_types(chosen_types)
    types = []
    chosen_types.each do |t|
      types << Discipline::DIS_TYPES[t]
    end
    types.join(", ")
  end

  def discipline_short_types(chosen_type)
    Discipline::SHORT_TYPES[chosen_type]
  end

  def discipline_end_types(chosen_type)
    Discipline::DIS_END[chosen_type]
  end

  def add_discipline_data(form)
    new_object = CommunityDiscipline.new
    fields = form.fields_for(:community_disciplines, new_object,
      :child_index => 'new_community_discipline') do |builder|
      render('community_disciplines/add_community_discipline', addy_form: builder)
    end
    {content: "#{fields}"}
  end

  def link_to_remove_dis(form)
    form.hidden_field(:_destroy, class: 'remove_fields') +
        link_to(?#, class: 'remove_fields remove_dis') do
      fa_icon('times', title: 'Удалить дисциплину')
    end
  end

end

app/views/disciplines/_form.html.haml
= form_for @discipline do |f|
  = error_messages_for @discipline

  .row
    .col-md-8
      .form-group
        = f.label :discipline_name
        = f.text_field :discipline_name, class: 'form-control'
        = f.error_messages_for(:discipline_name)
  .row
    .col-md-6
      .form-group
        = f.label :discipline_type
        - Discipline::DIS_TYPES.each do |k, v|
          %div
            = check_box_tag "discipline[discipline_type][]", k
            %span= v
    .col-md-6
      .form-group
        = f.label :discipline_end
        - Discipline::DIS_END.each do |k, v|
          %div
            = f.radio_button(:discipline_end, k)
            %span= v
  .row
    .col-md-6
      .form-group
        = f.label :term_id
        = f.select(:term_id, term_options(f.object.term_id), {}, class: 'form-control')
        = f.error_messages_for(:term_id)
  .row
    .col-md-6
      .form-group
        = f.label :ranking_algorithm_id
        = f.select(:ranking_algorithm_id, ranking_algorithm_options(f.object.term_id), {include_blank: true}, class: 'form-control')
        = f.error_messages_for(:ranking_algorithm_id)

  .row
    .col-md-6
      .form-group
        = f.submit t('helpers.submit.submit'), class: 'btn btn-primary'

app/views/disciplines/edit.html.haml
=breadcrumb_tag do
  %li
    Дисциплины
  %li
    =link_to(ellipsisize(@discipline.discipline_name.to_s), @discipline)
  %li.active
    Редактирование


%h1
  = t('helpers.editing')
  = Discipline.model_name.human

= render 'form'

app/views/disciplines/index.html.haml
%h1 Дисциплины
%br

- if @disciplines.blank?
  - if @current_role_user.present?
    - if @current_role_user.is_admin? || @current_role_user.is_moderator?
      .row
        .col-md-6
          .form-group{style: 'margin: 10px 0px 10px 5px; font-size: 18px;'}
            В системе пока не создано ни одной дисциплины!

- else
  .list-group
    - @disciplines.each do |discipline|
      = link_to(discipline, class: 'list-group-item') do
        = discipline.discipline_name
        .toright
          - discipline.discipline_type.each do |dis_type|
            %span.label.label-primary
              = discipline_short_types(dis_type)
          %span.label.label-info
            = discipline_end_types(discipline.discipline_end)
          - if @current_role_user.present?
            - if @current_role_user.is_admin? || @current_role_user.is_moderator?
              %span.label.label-success
                = discipline.term.term_name

        .clearfix
    = paginate @disciplines

- if @current_role_user.present?
  - if @current_role_user.is_admin? || @current_role_user.is_moderator?
    = link_to 'Новая дисциплина', new_discipline_path, class: "btn btn-success"

app/views/disciplines/new.html.haml
=breadcrumb_tag do
  %li
    Дисциплины
  %li.active
    Новая дисциплина


%h1 Новая дисциплина

= render 'form'

/= link_to 'Back', disciplines_path

app/views/disciplines/show.html.haml
=breadcrumb_tag do
  %li
    Дисциплины
  %li.active
    =link_to(ellipsisize(@discipline.discipline_name.to_s), @discipline)
%br

%p
  %b
    = Discipline.human_attribute_name(:discipline_name) + ":"
  = @discipline.discipline_name
%p
  %b
    = Discipline.human_attribute_name(:discipline_type) + ":"
  = discipline_types(@discipline.discipline_type)
%p
  %b
    = Discipline.human_attribute_name(:discipline_end) + ":"
  = discipline_end_types(@discipline.discipline_end)
%p
  %b
    = Discipline.human_attribute_name(:term_id) + ":"
  = @discipline.term.term_name
%p
  %b
    = Discipline.human_attribute_name(:ranking_algorithm_id) + ":"
  = @discipline.ranking_algorithm.algorithm_name

= link_to t('helpers.edit'), edit_discipline_path(@discipline), class: 'btn btn-warning'
= link_to t('helpers.destroy'), @discipline, :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: 'btn btn-danger'