config/routes.rb
Rails.application.routes.draw do
  resources :marks do
    collection do
      get :update_mark
    end
  end
  resources :discipline_sections
  resources :role_users do
    collection do
      get :mass_activation
      post :mass_activation_commit
    end
  end
  resources :community_newses
  resources :community_disciplines
  get 'students_api/load_from_json_file', as: :load_from_json_file_students_api
  post 'students_api/load_from_json_file'
  get 'students_api/load_to_json_file', as: :load_to_json_file_students_api
  #post 'students_api/load_to_json_file'

  get 'disciplines_api/load_from_json_file', as: :load_from_json_file_disciplines_api
  post 'disciplines_api/load_from_json_file'
  get 'disciplines_api/load_to_json_file', as: :load_to_json_file_disciplines_api

  get 'groups_api/load_from_json_file', as: :load_from_json_file_groups_api
  post 'groups_api/load_from_json_file'
  get 'groups_api/load_to_json_file', as: :load_to_json_file_groups_api

  get 'welcome/index', as: :index
  get 'welcome/insufficient_privileges', as: :ip

  resources :message_users
  resources :messages do
    member do
      get :show_file, as: :show_file
    end
  end
  resources :study_files
  resources :notices
  resources :institution_users
  resources :institutions
  resources :message_lists
  resources :community_contents
  resources :community_tabs
  resources :community_sections
  resources :community_users
  resources :communities do
    member do
      get :archiving
      get :dearchiving
    end
  end
  resources :disciplines
  resources :ranking_algorithms
  resources :groups
  resources :roles
  resources :terms
  root :to => 'welcome#index'
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/community_tab.rb
class CommunityTab < ApplicationRecord
 
  belongs_to :community_section
	has_many :community_contents

	validates :tab_name, presence: true, uniqueness: {scope: :community_section_id}
	validates :tab_position, presence: true,  numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than: 100 } 
	validates :community_section_id, presence: true

end

app/controllers/community_tabs_controller.rb
class CommunityTabsController < ApplicationController
  before_action :set_community_tab, only: [:show, :edit, :update, :destroy]

  # GET /community_tabs
  # GET /community_tabs.json
  def index
    @community_tabs = CommunityTab.all
  end

  # GET /community_tabs/1
  # GET /community_tabs/1.json
  def show
  end

  # GET /community_tabs/new
  def new
    @community_tab = CommunityTab.new
  end

  # GET /community_tabs/1/edit
  def edit
  end

  # POST /community_tabs
  # POST /community_tabs.json
  def create
    @community_tab = CommunityTab.new(community_tab_params)

    respond_to do |format|
      if @community_tab.save
        format.html { redirect_to @community_tab, notice: 'Community tab was successfully created.' }
        format.json { render :show, status: :created, location: @community_tab }
      else
        format.html { render :new }
        format.json { render json: @community_tab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /community_tabs/1
  # PATCH/PUT /community_tabs/1.json
  def update
    respond_to do |format|
      if @community_tab.update(community_tab_params)
        format.html { redirect_to @community_tab, notice: 'Community tab was successfully updated.' }
        format.json { render :show, status: :ok, location: @community_tab }
      else
        format.html { render :edit }
        format.json { render json: @community_tab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /community_tabs/1
  # DELETE /community_tabs/1.json
  def destroy
    @community_tab.destroy
    respond_to do |format|
      format.html { redirect_to community_tabs_url, notice: 'Community tab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community_tab
      @community_tab = CommunityTab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_tab_params
      params.require(:community_tab).permit(:community_section_id, :tab_name, :tab_position)
    end
end

app/helpers/community_tabs_helper.rb
module CommunityTabsHelper

  def community_section_options(selected)
		options_for_select(CommunitySection.all.map{ |cs| ["#{cs.section_name} ", cs.id] }, selected)
  end

end

app/views/community_tabs/_form.html.haml
= form_for @community_tab do |f|
  - if @community_tab.errors.any?
    #error_explanation
      %h2= "#{pluralize(@community_tab.errors.count, "error")} prohibited this community_tab from being saved:"
      %ul
        - @community_tab.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :community_section_id
    = f.select(:community_section_id, community_section_options(f.object.community_section_id))
  .field
    = f.label :tab_name
    = f.text_field :tab_name
  .field
    = f.label :tab_position
    = f.number_field :tab_position
  .actions
    = f.submit 'Save'

app/views/community_tabs/edit.html.haml
%h1 Editing community_tab

= render 'form'

= link_to 'Show', @community_tab
\|
= link_to 'Back', community_tabs_path

app/views/community_tabs/index.html.haml
%h1 Listing community_tabs

%table
  %thead
    %tr
      %th Community section
      %th Tab name
      %th Tab position
      %th
      %th
      %th

  %tbody
    - @community_tabs.each do |community_tab|
      %tr
        %td= community_tab.community_section.section_name
        %td= community_tab.tab_name
        %td= community_tab.tab_position
        %td= link_to 'Show', community_tab
        %td= link_to 'Edit', edit_community_tab_path(community_tab)
        %td= link_to 'Destroy', community_tab, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Community tab', new_community_tab_path

app/views/community_tabs/new.html.haml
%h1 New community_tab

= render 'form'

= link_to 'Back', community_tabs_path

app/views/community_tabs/show.html.haml
%p#notice= notice

%p
  %b Community section:
  = @community_tab.community_section
%p
  %b Tab name:
  = @community_tab.tab_name
%p
  %b Tab position:
  = @community_tab.tab_position

= link_to 'Edit', edit_community_tab_path(@community_tab)
\|
= link_to 'Back', community_tabs_path