config/routes.rb
Rails.application.routes.draw do
  resources :marks do
    collection do
      get :update_mark
    end
  end
  resources :discipline_sections
  resources :role_users do
    collection do
      get :mass_activation
      post :mass_activation_commit
    end
  end
  resources :community_newses
  resources :community_disciplines
  get 'students_api/load_from_json_file', as: :load_from_json_file_students_api
  post 'students_api/load_from_json_file'
  get 'students_api/load_to_json_file', as: :load_to_json_file_students_api
  #post 'students_api/load_to_json_file'

  get 'disciplines_api/load_from_json_file', as: :load_from_json_file_disciplines_api
  post 'disciplines_api/load_from_json_file'
  get 'disciplines_api/load_to_json_file', as: :load_to_json_file_disciplines_api

  get 'groups_api/load_from_json_file', as: :load_from_json_file_groups_api
  post 'groups_api/load_from_json_file'
  get 'groups_api/load_to_json_file', as: :load_to_json_file_groups_api

  get 'welcome/index', as: :index
  get 'welcome/insufficient_privileges', as: :ip

  resources :message_users
  resources :messages do
    member do
      get :show_file, as: :show_file
    end
  end
  resources :study_files
  resources :notices
  resources :institution_users
  resources :institutions
  resources :message_lists
  resources :community_contents
  resources :community_tabs
  resources :community_sections
  resources :community_users
  resources :communities do
    member do
      get :archiving
      get :dearchiving
    end
  end
  resources :disciplines
  resources :ranking_algorithms
  resources :groups
  resources :roles
  resources :terms
  root :to => 'welcome#index'
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
  belongs_to :community_section

  validates :notice_type, presence: true, inclusion: { in: [0, 1, 2] }
  validates :community_section_id, presence: true, uniqueness: {scope: :user_id}
  validates :user_id, presence: true
  
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:notice_type, :user_id, :community_section_id)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
 
  def type_options(selected)
		types = {0=>'не уведомлять', 1=>'уведомлять на сайте', 2=>'уведомлять на сайте и по электронной почте'}
		options_for_select(types.map { |k, v| [v, k]}, selected)
  end

  def user_options(selected)
		options_for_select(User.all.map{ |us| ["#{us.last_name} #{us.first_name} #{us.second_name} ", us.id] }, selected)
  end

  def community_section_options(selected)
		options_for_select(CommunitySection.all.map{ |cs| ["#{cs.section_name} ", cs.id] }, selected)
  end

end

app/views/notices/_form.html.haml
= form_for @notice do |f|
  - if @notice.errors.any?
    #error_explanation
      %h2= "#{pluralize(@notice.errors.count, "error")} prohibited this notice from being saved:"
      %ul
        - @notice.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :notice_type
    = f.select(:notice_type, type_options(f.object.notice_type))
  .field
    = f.label :user_id
    = f.select(:user_id, user_options(f.object.user_id))
  .field
    = f.label :community_section_id
    = f.select(:community_section_id, community_section_options(f.object.community_section_id))
  .actions
    = f.submit 'Save'

app/views/notices/edit.html.haml
%h1 Editing notice

= render 'form'

= link_to 'Show', @notice
\|
= link_to 'Back', notices_path

app/views/notices/index.html.haml
%h1 Listing notices

%table
  %thead
    %tr
      %th Notice type
      %th User
      %th
      %th
      %th Community section
      %th
      %th
      %th

  %tbody
    - @notices.each do |notice|
      %tr
        %td= notice.notice_type
        %td= notice.user.last_name
        %td= notice.user.first_name
        %td= notice.user.second_name
        %td= notice.community_section.section_type
        %td= link_to 'Show', notice
        %td= link_to 'Edit', edit_notice_path(notice)
        %td= link_to 'Destroy', notice, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Notice', new_notice_path

app/views/notices/new.html.haml
%h1 New notice

= render 'form'

= link_to 'Back', notices_path

app/views/notices/show.html.haml
%p#notice= notice

%p
  %b Notice type:
  = @notice.notice_type
%p
  %b User:
  = @notice.user
%p
  %b Community section:
  = @notice.community_section

= link_to 'Edit', edit_notice_path(@notice)
\|
= link_to 'Back', notices_path