config/routes.rb
Rails.application.routes.draw do
  resources :marks do
    collection do
      get :update_mark
    end
  end
  resources :discipline_sections
  resources :role_users do
    collection do
      get :mass_activation
      post :mass_activation_commit
    end
  end
  resources :community_newses
  resources :community_disciplines
  get 'students_api/load_from_json_file', as: :load_from_json_file_students_api
  post 'students_api/load_from_json_file'
  get 'students_api/load_to_json_file', as: :load_to_json_file_students_api
  #post 'students_api/load_to_json_file'

  get 'disciplines_api/load_from_json_file', as: :load_from_json_file_disciplines_api
  post 'disciplines_api/load_from_json_file'
  get 'disciplines_api/load_to_json_file', as: :load_to_json_file_disciplines_api

  get 'groups_api/load_from_json_file', as: :load_from_json_file_groups_api
  post 'groups_api/load_from_json_file'
  get 'groups_api/load_to_json_file', as: :load_to_json_file_groups_api

  get 'welcome/index', as: :index
  get 'welcome/insufficient_privileges', as: :ip

  resources :message_users
  resources :messages do
    member do
      get :show_file, as: :show_file
    end
  end
  resources :study_files
  resources :notices
  resources :institution_users
  resources :institutions
  resources :message_lists
  resources :community_contents
  resources :community_tabs
  resources :community_sections
  resources :community_users
  resources :communities do
    member do
      get :archiving
      get :dearchiving
    end
  end
  resources :disciplines
  resources :ranking_algorithms
  resources :groups
  resources :roles
  resources :terms
  root :to => 'welcome#index'
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/community_content.rb
class CommunityContent < ApplicationRecord
  belongs_to :community_tab
  belongs_to :creator, :class_name => 'User'

  validates :view_type, presence: true, inclusion: { in: [0, 1] } # html или markdown
  validates :content_body, presence: true
  validates :content_visibility, presence: true, inclusion: { in: [0, 1, 2] }
  validates :community_tab_id, presence: true
  validates :creator_id, presence: true

end

app/controllers/community_contents_controller.rb
class CommunityContentsController < ApplicationController
  before_action :set_community_content, only: [:show, :edit, :update, :destroy]

  # GET /community_contents
  # GET /community_contents.json
  def index
    @community_contents = CommunityContent.all
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    example = '
  *This is example*
  
  1. qq
  1. qq  
  1. qq

  ***dada***  
    '
    @example = markdown.render(example)
  end

  # GET /community_contents/1
  # GET /community_contents/1.json
  def show
  end

  # GET /community_contents/new
  def new
    @community_content = CommunityContent.new
  end

  # GET /community_contents/1/edit
  def edit
  end

  # POST /community_contents
  # POST /community_contents.json
  def create
    @community_content = CommunityContent.new(community_content_params)

    respond_to do |format|
      if @community_content.save
        format.html { redirect_to @community_content, notice: 'Community content was successfully created.' }
        format.json { render :show, status: :created, location: @community_content }
      else
        format.html { render :new }
        format.json { render json: @community_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /community_contents/1
  # PATCH/PUT /community_contents/1.json
  def update
    respond_to do |format|
      if @community_content.update(community_content_params)
        format.html { redirect_to @community_content, notice: 'Community content was successfully updated.' }
        format.json { render :show, status: :ok, location: @community_content }
      else
        format.html { render :edit }
        format.json { render json: @community_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /community_contents/1
  # DELETE /community_contents/1.json
  def destroy
    @community_content.destroy
    respond_to do |format|
      format.html { redirect_to community_contents_url, notice: 'Community content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community_content
      @community_content = CommunityContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_content_params
      params.require(:community_content).permit(:view_type, :content_body, :content_visibility, :show, :community_tab_id, :creator_id)
    end
end

app/helpers/community_contents_helper.rb
module CommunityContentsHelper

  def view_type_options(selected)
		types = {0=>'html', 1=>'markdown'}
		options_for_select(types.map { |k, v| [v, k]}, selected)
   end

   def visibility_options(selected)
		types = {0=>'виден всем участникам сообщества', 1=>'виден только владельцу и модераторам/редакторам сообщества', 2=>'отложенная публикация'}
		options_for_select(types.map { |k, v| [v, k]}, selected)
  end

  def community_tab_options(selected)
		options_for_select(CommunityTab.all.map{ |ct| ["#{ct.tab_name} ", ct.id] }, selected)
  end

  def user_options(selected)
		options_for_select(User.all.map{ |us| ["#{us.last_name} #{us.first_name} #{us.second_name} ", us.id] }, selected)
  end

end

app/views/community_contents/_form.html.haml
= form_for @community_content do |f|
  - if @community_content.errors.any?
    #error_explanation
      %h2= "#{pluralize(@community_content.errors.count, "error")} prohibited this community_content from being saved:"
      %ul
        - @community_content.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :view_type
    = f.select(:view_type, view_type_options(f.object.view_type))
  .field
    = f.label :content_body
    = f.text_area :content_body
  .field
    = f.label :content_visibility
    = f.select(:content_visibility, visibility_options(f.object.content_visibility))
  .field
    = f.label :show
    = f.datetime_select :show
  .field
    = f.label :community_tab_id
    = f.select(:community_tab_id, community_tab_options(f.object.community_tab_id))
  .field
    = f.label :creator_id
    = f.select(:creator_id, user_options(f.object.creator_id))
  .actions
    = f.submit 'Save'

app/views/community_contents/edit.html.haml
%h1 Editing community_content

= render 'form'

= link_to 'Show', @community_content
\|
= link_to 'Back', community_contents_path

app/views/community_contents/index.html.haml
%h1 Listing community_contents

%div
  = raw(@example)

%table
  %thead
    %tr
      %th View type
      %th Content body
      %th Content visibility
      %th Show
      %th Community tab
      %th Creator
      %th
      %th
      %th
      %th
      %th

  %tbody
    - @community_contents.each do |community_content|
      %tr
        %td= community_content.view_type
        %td= community_content.content_body
        %td= community_content.content_visibility
        %td= community_content.show
        %td= community_content.community_tab.tab_name
        %td= community_content.creator.last_name
        %td= community_content.creator.first_name
        %td= community_content.creator.second_name
        %td= link_to 'Show', community_content
        %td= link_to 'Edit', edit_community_content_path(community_content)
        %td= link_to 'Destroy', community_content, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Community content', new_community_content_path

app/views/community_contents/new.html.haml
%h1 New community_content

= render 'form'

= link_to 'Back', community_contents_path

app/views/community_contents/show.html.haml
%p#notice= notice

%p
  %b View type:
  = @community_content.view_type
%p
  %b Content body:
  = @community_content.content_body
%p
  %b Content visibility:
  = @community_content.content_visibility
%p
  %b Show:
  = @community_content.show
%p
  %b Community tab:
  = @community_content.community_tab
%p
  %b Creator:
  = @community_content.creator

= link_to 'Edit', edit_community_content_path(@community_content)
\|
= link_to 'Back', community_contents_path